[2024-03-22T18:50:06.719+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: milestone3.clean_data scheduled__2024-03-22T18:48:00+00:00 [queued]>
[2024-03-22T18:50:06.726+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: milestone3.clean_data scheduled__2024-03-22T18:48:00+00:00 [queued]>
[2024-03-22T18:50:06.726+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-03-22T18:50:06.726+0000] {taskinstance.py:1369} INFO - Starting attempt 2 of 2
[2024-03-22T18:50:06.726+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-03-22T18:50:06.737+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): clean_data> on 2024-03-22 18:48:00+00:00
[2024-03-22T18:50:06.748+0000] {standard_task_runner.py:52} INFO - Started process 1849 to run task
[2024-03-22T18:50:06.752+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'milestone3', 'clean_data', 'scheduled__2024-03-22T18:48:00+00:00', '--job-id', '200', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_elia_DAG.py', '--cfg-path', '/tmp/tmpdyv78b86', '--error-file', '/tmp/tmpkhwt0xrc']
[2024-03-22T18:50:06.754+0000] {standard_task_runner.py:80} INFO - Job 200: Subtask clean_data
[2024-03-22T18:50:06.831+0000] {task_command.py:371} INFO - Running <TaskInstance: milestone3.clean_data scheduled__2024-03-22T18:48:00+00:00 [running]> on host b79cb602ca97
[2024-03-22T18:50:06.883+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=elia
AIRFLOW_CTX_DAG_ID=milestone3
AIRFLOW_CTX_TASK_ID=clean_data
AIRFLOW_CTX_EXECUTION_DATE=2024-03-22T18:48:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-22T18:48:00+00:00
[2024-03-22T18:50:06.967+0000] {logging_mixin.py:115} INFO -        index      Date    Year  ...    Cost      Revenue Column1
0          0  02/19/16  2016.0  ...    80.0   109.000000     NaN
1          1  02/20/16  2016.0  ...    49.0    57.000000     NaN
2          2  02/27/16  2016.0  ...    11.0    15.000000     NaN
3          3  03/12/16  2016.0  ...   175.0   233.000000     NaN
4          4  03/12/16  2016.0  ...   105.0   125.000000     NaN
...      ...       ...     ...  ...     ...          ...     ...
34862  34862  02/07/16  2016.0  ...  2320.0  1971.000000     NaN
34863  34863  03/13/15  2015.0  ...  2049.0  1583.000000     NaN
34864  34864  04/05/15  2015.0  ...  2049.0  1682.000000     NaN
34865  34865  08/30/15  2015.0  ...  2320.0  1568.000000     NaN
34866  34866       NaN     NaN  ...     NaN   641.532095     NaN

[34867 rows x 16 columns]
[2024-03-22T18:50:06.999+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/P2M3_elia_DAG.py", line 46, in clean
    df=df.dropna(subset=['Date']) #drop null data row (no information)
AttributeError: 'NoneType' object has no attribute 'dropna'
[2024-03-22T18:50:07.016+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=milestone3, task_id=clean_data, execution_date=20240322T184800, start_date=20240322T185006, end_date=20240322T185007
[2024-03-22T18:50:07.024+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 200 for task clean_data ('NoneType' object has no attribute 'dropna'; 1849)
[2024-03-22T18:50:07.064+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-22T18:50:07.134+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
